//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int ID { get; set; }
        public string Content { get; set; }
        public System.DateTime SendingDate { get; set; }
        public int TopicID { get; set; }
        public int SenderID { get; set; }
        public int RecieverID { get; set; }
    
        public virtual Addresser Reciever { get; set; }
        public virtual Addresser Sender { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
