//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CourseWorkEntities : DbContext
    {
        public CourseWorkEntities()
            : base("name=CourseWorkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addresser> Addressers { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
    
        public virtual ObjectResult<GetTopicReport_Result> GetTopicReport(Nullable<int> topicID)
        {
            var topicIDParameter = topicID.HasValue ?
                new ObjectParameter("TopicID", topicID) :
                new ObjectParameter("TopicID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTopicReport_Result>("GetTopicReport", topicIDParameter);
        }
    
        public virtual ObjectResult<GetWorkReport_Result> GetWorkReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWorkReport_Result>("GetWorkReport");
        }
    }
}
